"""fix aboute_me to about_me user's field

Revision ID: 617615b2855f
Revises: c84ec97dad3d
Create Date: 2019-04-03 09:59:34.440005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617615b2855f'
down_revision = 'c84ec97dad3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.drop_column('user', 'aboute_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aboute_me', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
