"""adding about_me and last_seen user's fields

Revision ID: c84ec97dad3d
Revises: 8c3eebb7c3e9
Create Date: 2019-04-03 08:58:27.679812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84ec97dad3d'
down_revision = '8c3eebb7c3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aboute_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'aboute_me')
    # ### end Alembic commands ###
